CREATE TABLE `markets` (
	`coin_id` text PRIMARY KEY NOT NULL,
	`symbol` text NOT NULL,
	`name` text NOT NULL,
	`image` text,
	`current_price` real,
	`market_cap` real,
	`market_cap_rank` integer,
	`fully_diluted_valuation` real,
	`total_volume` real,
	`high_24h` real,
	`low_24h` real,
	`price_change_24h` real,
	`price_change_percentage_24h` real,
	`market_cap_change_24h` real,
	`market_cap_change_percentage_24h` real,
	`price_change_percentage_1h_in_currency` real,
	`circulating_supply` real,
	`total_supply` real,
	`max_supply` real,
	`ath` real,
	`ath_change_percentage` real,
	`ath_date` text,
	`atl` real,
	`atl_change_percentage` real,
	`atl_date` text,
	`roi` text,
	`last_updated` text,
	`raw` text,
	`updated_at` integer DEFAULT (unixepoch('subsec') * 1000) NOT NULL
);
